spring.application.name=auth-service
server.port=8081

spring.datasource.url=${USERS_DB_URL:jdbc:postgresql://localhost:5432/sicaeUsuario}
spring.datasource.username=${USERS_DB_USER:sicae_usuario_app}
spring.datasource.password=${USERS_DB_PASSWORD:sicae123}
spring.datasource.driver-class-name=org.postgresql.Driver

mybatis.configuration.map-underscore-to-camel-case=true

jwt.secret=${JWT_SECRET:sicae-dev-secret-key-muy-larga-y-segura-12345}
jwt.expiration=86400000
