spring.application.name=parking-service
server.port=8084

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3308/sicaeEstacionamiento?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=America/Mexico_City}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:sicae_estacionamiento_app}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:sicae123}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

mybatis.configuration.map-underscore-to-camel-case=false

user.service.soap.url=${USER_SERVICE_SOAP_URL:http://localhost:8082/ws}
vehicle.service.rest.url=${VEHICLE_SERVICE_REST_URL:http://localhost:8083/api/vehiculos}
jwt.secret=${JWT_SECRET:sicae-dev-secret-key-muy-larga-y-segura-12345}
